Feature/#30
wafflestudio/wafflestudio.com-v2 pull request #46
Opened 2022-01-04 12:49 UTC by ars-ki-00

2022-01-13 00:38 UTC, woohm402 requested changes
완성한거 캡쳐해서 PR에 첨부해주세요~

2022-01-13 00:38 UTC, woohm402 commented on package-lock.json
> +      "resolved": "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz",
먼데이거

2022-01-13 00:38 UTC, woohm402 commented on package-lock.json
> +      "resolved": "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz",
왜수정댐

2022-01-13 00:38 UTC, woohm402 commented on src/components/common/layout.scss
> +}
막줄 엔터요

2022-01-13 00:38 UTC, woohm402 commented on src/components/common/navigation/navigation.module.scss
> +}
프리티어라는 친구가 있는데 그거 돌리면 막줄 엔터 자동으로 넣어주거든요

2022-01-13 00:38 UTC, woohm402 commented on src/components/index/banner/banner.module.scss
> +}
;;

2022-01-13 00:38 UTC, woohm402 commented on src/components/index/banner/banner.module.scss
> +
불필요한 엔터 제거 요망

2022-01-13 00:38 UTC, woohm402 commented on src/components/index/banner/banner.tsx
> +          <div className={styles.box}></div>
eslint rule 추가해야겠다 이거

2022-01-13 00:38 UTC, woohm402 commented on src/components/index/banner/banner.tsx
> +          <div className={styles.box}></div>
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md

2022-01-13 00:38 UTC, woohm402 commented on src/components/index/banner/banner.tsx
> +          <div className={styles.box}></div>
#47

2022-01-13 00:38 UTC, woohm402 commented on src/components/index/banner/banner.tsx
> +          <div className={styles.box}></div>
암튼 열면서 바로 닫는 걸로 고쳐주셍요

2022-01-15 06:39 UTC, ars-ki-00 commented on package-lock.json
> +      "resolved": "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz",
나도 몰러 돌리니까 수정됐는데 어카누 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-01-15 06:44 UTC, ars-ki-00 commented on src/components/common/navigation/navigation.module.scss
> +}
format on save 안 되어 있었네 ㄷ ㄷ

2022-01-15 06:44 UTC, ars-ki-00 commented on src/components/index/banner/banner.tsx
> +          <div className={styles.box}></div>
😲

2022-01-15 06:44 UTC, ars-ki-00 commented on src/components/index/banner/banner.tsx
> +          <div className={styles.box}></div>
나중에 뭐라도 들어가지 않을까

2022-01-15 06:50 UTC, woohm402 commented on src/components/common/navigation/navigation.module.scss
> +}
;;;;;

2022-01-15 06:50 UTC, woohm402 commented on src/components/index/banner/banner.tsx
> +          <div className={styles.box}></div>
ㄴㄴ그럴리가

2022-01-15 06:51 UTC, woohm402 commented on package-lock.json
> +      "resolved": "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz",
,,,,

2022-01-15 07:00 UTC, woohm402 approved these changes

2022-01-15 07:02 UTC, merged